[package]
name = "tokentask"
version = "0.1.0"
edition = "2024"

[dependencies]
bon = "3.8.1"
oauth2 = { version = "5.0.0", optional = true }
tracing = "0.1.41"


[features]
oauth = ["oauth2"]
default = ["oauth"]
full = ["oauth"]
